language: python
python:
 - "3.6"

branches:
  only:
    - master

install:
 - pip install html5validator

script: html5validator --root _build/


deploy:
  provider: surge
  project: /home/vagrant
  domain: palomagarciacampon.surge.sh
  skip_cleanup: true
  
