language: python
python:
 - "3.6"

branches:
  only:
    - master

install:
 - pip install html5validator

script: html5validator --root _build/

SURGE_LOGIN=palomagarciacampon08@gmail.com
SURGE_TOKEN=44e3cb815daaa333695d238bc6f62692

deploy:
  provider: surge
  project: ./_build/
  domain: palomagarciacampon.surge.sh
  skip_cleanup: true
  
